export const FORM_INPUT_SELECTOR = '.js-form-input'
export const FORM_BTN_SELECTOR = '.js-form-btn'
export const FORM_MESSAGE_SELECTOR = '.js-form-message'
export const FEEDS_SELECTOR = '.js-feeds'
export const POSTS_SELECTOR = '.js-posts'
export const MODAL_TITLE_SELECTOR = '.js-modal-title'
export const MODAL_DESCRIPTION_SELECTOR = '.js-modal-description'
export const MODAL_LINK_SELECTOR = '.js-modal-link'
